/* -*- sv -*- File generated by the BNF Converter (bnfc 2.9.7). */

/*******************************************************/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

`include "json/JSONInterpBase.svh"


task InterpBase::visitJSON(JSON p); endtask //abstract class
task InterpBase::visitValue(Value p); endtask //abstract class
task InterpBase::visitMember_Item(Member_Item p); endtask //abstract class
task InterpBase::visitString_Literal(String_Literal p); endtask //abstract class

task InterpBase::visitJSONValue(JSONValue p);
  /* Code For JSONValue Goes Here */

  p.value_.accept(this);

endtask

task InterpBase::visitObjectVal(ObjectVal p);
  /* Code For ObjectVal Goes Here */

  p.listmember_item_.accept(this);

endtask

task InterpBase::visitArrayVal(ArrayVal p);
  /* Code For ArrayVal Goes Here */

  p.listvalue_.accept(this);

endtask

task InterpBase::visitStringVal(StringVal p);
  /* Code For StringVal Goes Here */

  p.string_literal_.accept(this);

endtask

task InterpBase::visitScientificNumberVal(ScientificNumberVal p);
  /* Code For ScientificNumberVal Goes Here */

  visitScientificNum(p.scientificnum_);

endtask

task InterpBase::visitDecimalNumberVal(DecimalNumberVal p);
  /* Code For DecimalNumberVal Goes Here */

  visitDecimalNum(p.decimalnum_);

endtask

task InterpBase::visitIntegerNumberVal(IntegerNumberVal p);
  /* Code For IntegerNumberVal Goes Here */

  visitIntegerNum(p.integernum_);

endtask

task InterpBase::visitTrueVal(TrueVal p);
  /* Code For TrueVal Goes Here */


endtask

task InterpBase::visitFalseVal(FalseVal p);
  /* Code For FalseVal Goes Here */


endtask

task InterpBase::visitNullVal(NullVal p);
  /* Code For NullVal Goes Here */


endtask

task InterpBase::visitMember(Member p);
  /* Code For Member Goes Here */

  p.string_literal_.accept(this);
  p.value_.accept(this);

endtask

task InterpBase::visitStringLit(StringLit p);
  /* Code For StringLit Goes Here */

  visitAnyChars(p.anychars_);

endtask


task InterpBase::visitListMember_Item(ListMember_Item  listmember_item);
  for ( int i = 0; i < listmember_item.v.size() ; i++)
  begin
    listmember_item.v[i].accept(this);
  end
endtask

task InterpBase::visitListValue(ListValue  listvalue);
  for ( int i = 0; i < listvalue.v.size() ; i++)
  begin
    listvalue.v[i].accept(this);
  end
endtask


task InterpBase::visitIntegerNum(IntegerNum x);
  /* Code for IntegerNum Goes Here */
endtask

task InterpBase::visitDecimalNum(DecimalNum x);
  /* Code for DecimalNum Goes Here */
endtask

task InterpBase::visitScientificNum(ScientificNum x);
  /* Code for ScientificNum Goes Here */
endtask

task InterpBase::visitAnyChars(AnyChars x);
  /* Code for AnyChars Goes Here */
endtask

task InterpBase::visitInteger(Integer x);
  /* Code for Integer Goes Here */
endtask

task InterpBase::visitChar(Char x);
  /* Code for Char Goes Here */
endtask

task InterpBase::visitDouble(Double x);
  /* Code for Double Goes Here */
endtask

task InterpBase::visitString(String x);
  /* Code for String Goes Here */
endtask

task InterpBase::visitIdent(Ident x);
  /* Code for Ident Goes Here */
endtask



