/* -*- sv -*- File generated by the BNF Converter (bnfc 2.9.7). */


`ifndef JSON_SVIO_PKG_SVH
`define JSON_SVIO_PKG_SVH

package json_pkg;

`include "json/JSONAbsyn.svh"
`include "json/JSONParser.svh"
`include "json/json.sv"
`include "json/JSONInterpBase.svh"
`include "json/JSONInterp.svh"
`include "json/JSONPrinter.svh"

  // Constructor helpers for the Val_ class hierarchy. Useful for code that
  // builds a JSON value tree programmatically (e.g., a generator-emitted
  // toJSON() that needs to wrap an int / string / bool field as a Val_).
  function automatic Val_ mkInt(longint x);
    IntVal_ v = new(x);
    return v;
  endfunction

  function automatic Val_ mkReal(real x);
    RealVal_ v = new(x);
    return v;
  endfunction

  function automatic Val_ mkStr(string x);
    StringVal_ v = new(x);
    return v;
  endfunction

  function automatic Val_ mkBool(bit x);
    BoolVal_ v = new(x);
    return v;
  endfunction

  // Generated shared runtime helpers.
  // Keep grammar-specific semantic state and symbol/environment machinery
  // in the preserved Interp user files instead of this package support.

  // Returns the index of first occurrence of string 'sub' within string 's''s given index range.
  // Returns -1 otherwise.
  function automatic int str_find(string s, string sub, int range_lo = 0, int range_hi = -1);
    if (range_hi < 0 || range_hi >= s.len()) range_hi = s.len() - 1;
    for (int i = range_lo; i <= (range_hi - sub.len() + 1); i++) begin
      if (s.substr(i, i + sub.len() - 1) == sub) begin
        return i;
      end
    end
    return -1;
  endfunction : str_find

  // Find the first match string 'sub' in 's' and replace it with 'new_sub'.
  // TODO: Add support for global replacement.
  function automatic string str_replace(string s, string sub, string new_sub);
    string str_before_sub, str_after_sub;
    int lo_idx = str_find(s, sub);

    if (!(lo_idx != -1))
      return s;

    if (lo_idx > 0) str_before_sub = s.substr(0, lo_idx - 1);
    if (lo_idx + sub.len() < s.len()) str_after_sub = s.substr(lo_idx + sub.len(), s.len() - 1);

    return {str_before_sub, new_sub, str_after_sub};
  endfunction : str_replace


`include "json/JSONAbsyn.sv"
`include "json/JSONInterpBase.sv"
`include "json/JSONInterp.sv"
`include "json/JSONPrinter.sv"

  /* Entrypoint: parse JSON from file. */
  function Val_ pJSON(string filename);
    automatic Parser p = new();
    p.b = Bopen(filename, `OREAD);
    p.yy_mylinenumber = 1;
    p.initialize_lexer(0);
    if (p.yyparse())
      return null; /* Failure */
    else begin
      automatic Interp i = new();
      i.interpret(p.YY_RESULT_JSON_);
      return i.get_json_val();
    end
  endfunction

  /* Entrypoint: parse JSON from string. */
  function Val_ psJSON(string str);
  automatic Parser p = new();
    p.b = Bopens(str);
    p.yy_mylinenumber = 1;
    p.initialize_lexer(0);
    if (p.yyparse())
      return null; /* Failure */
    else begin
      automatic Interp i = new();
      i.interpret(p.YY_RESULT_JSON_);
      return i.get_json_val();
    end
  endfunction

endpackage

`endif
