/* -*- sv -*- File generated by the BNF Converter (bnfc 2.9.6). */

`ifndef ABSYN_HEADER
`define ABSYN_HEADER

typedef class Visitor;

//************************************************************.

/********************   TypeDef Section    ********************/

typedef int Integer;
typedef string Char;
typedef real Double;
typedef string String;
typedef string Ident;

typedef string IntegerNum;
typedef string DecimalNum;
typedef string ScientificNum;
typedef string AnyChars;

/********************   Forward Declarations    ********************/

typedef class JSON;
typedef class Value;
typedef class Member_Item;
typedef class String_Literal;
typedef class JSONValue;
typedef class ObjectVal;
typedef class ArrayVal;
typedef class StringVal;
typedef class ScientificNumberVal;
typedef class DecimalNumberVal;
typedef class IntegerNumberVal;
typedef class TrueVal;
typedef class FalseVal;
typedef class NullVal;
typedef class Member;
typedef class StringLit;
typedef class ListMember_Item;
typedef class ListValue;

/********************   Visitor Interfaces    ********************/
interface class Visitor;
  pure virtual task visitJSON(JSON p);
  pure virtual task visitValue(Value p);
  pure virtual task visitMember_Item(Member_Item p);
  pure virtual task visitString_Literal(String_Literal p);
  pure virtual task visitJSONValue(JSONValue p);
  pure virtual task visitObjectVal(ObjectVal p);
  pure virtual task visitArrayVal(ArrayVal p);
  pure virtual task visitStringVal(StringVal p);
  pure virtual task visitScientificNumberVal(ScientificNumberVal p);
  pure virtual task visitDecimalNumberVal(DecimalNumberVal p);
  pure virtual task visitIntegerNumberVal(IntegerNumberVal p);
  pure virtual task visitTrueVal(TrueVal p);
  pure virtual task visitFalseVal(FalseVal p);
  pure virtual task visitNullVal(NullVal p);
  pure virtual task visitMember(Member p);
  pure virtual task visitStringLit(StringLit p);


  pure virtual task visitListMember_Item(ListMember_Item listmember_item);
  pure virtual task visitListValue(ListValue listvalue);

  pure virtual task visitInteger(Integer x);
  pure virtual task visitChar(Char x);
  pure virtual task visitDouble(Double x);
  pure virtual task visitString(String x);
  pure virtual task visitIdent(Ident x);
  pure virtual task visitIntegerNum(IntegerNum x);
  pure virtual task visitDecimalNum(DecimalNum x);
  pure virtual task visitScientificNum(ScientificNum x);
  pure virtual task visitAnyChars(AnyChars x);

endclass

interface class Visitable;
  pure virtual task accept(Visitor v);
endclass

/********************   Abstract Syntax Classes    ********************/

virtual class JSON implements Visitable;
  int line_number;
  virtual task accept(Visitor v); endtask
endclass

virtual class Value implements Visitable;
  int line_number;
  virtual task accept(Visitor v); endtask
endclass

virtual class Member_Item implements Visitable;
  int line_number;
  virtual task accept(Visitor v); endtask
endclass

virtual class String_Literal implements Visitable;
  int line_number;
  virtual task accept(Visitor v); endtask
endclass


class JSONValue extends JSON;
  Value value_;

  extern function new(Value p1);
  extern virtual task accept(Visitor v);
endclass

class ObjectVal extends Value;
  ListMember_Item listmember_item_;

  extern function new(ListMember_Item p1);
  extern virtual task accept(Visitor v);
endclass

class ArrayVal extends Value;
  ListValue listvalue_;

  extern function new(ListValue p1);
  extern virtual task accept(Visitor v);
endclass

class StringVal extends Value;
  String_Literal string_literal_;

  extern function new(String_Literal p1);
  extern virtual task accept(Visitor v);
endclass

class ScientificNumberVal extends Value;
  ScientificNum scientificnum_;

  extern function new(ScientificNum p1);
  extern virtual task accept(Visitor v);
endclass

class DecimalNumberVal extends Value;
  DecimalNum decimalnum_;

  extern function new(DecimalNum p1);
  extern virtual task accept(Visitor v);
endclass

class IntegerNumberVal extends Value;
  IntegerNum integernum_;

  extern function new(IntegerNum p1);
  extern virtual task accept(Visitor v);
endclass

class TrueVal extends Value;

  extern function new();
  extern virtual task accept(Visitor v);
endclass

class FalseVal extends Value;

  extern function new();
  extern virtual task accept(Visitor v);
endclass

class NullVal extends Value;

  extern function new();
  extern virtual task accept(Visitor v);
endclass

class Member extends Member_Item;
  String_Literal string_literal_;
  Value value_;

  extern function new(String_Literal p1, Value p2);
  extern virtual task accept(Visitor v);
endclass

class StringLit extends String_Literal;
  AnyChars anychars_;

  extern function new(AnyChars p1);
  extern virtual task accept(Visitor v);
endclass


class ListMember_Item implements Visitable;
  Member_Item  v[$];
  extern virtual task accept(Visitor v);
endclass

class ListValue implements Visitable;
  Value  v[$];
  extern virtual task accept(Visitor v);
endclass




`endif
