/* -*- sv -*- File generated by the BNF Converter (bnfc 2.9.6). */

/****************************************************************************/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/

import json_pkg::*;

program automatic test;

  initial begin : prog
    automatic string filename = "test.w";
    automatic JSON parse_tree;
    automatic Interp i = new();
    automatic PrintAbsyn p = new();
    automatic ShowAbsyn q = new();

    automatic string json_str = "{ \"a\" : [ 1, 2, \"array_added_text\" ],\n \"f\" : false, \"i\" : 123, \"n\" : null,\n \"o\" : { \"2\" : 2, \"3\" : 3,\n \"inner_obj\" : { \"auth\" : \"zcr\", \"grade\" : 5 } }\n , \"s\" : \"abc\", \"t\" : true }          \n";

    if ($value$plusargs("input=%s", filename))
      parse_tree = pJSON(filename);
    else
    begin
      $write("%s\n", json_str);
      parse_tree = psJSON(json_str);
    end
    if (parse_tree) begin

      p.print(parse_tree);
      //$write("%s\n", p.buf_);

      q.show(parse_tree);
      //$write("%s\n", q.buf_);
      i.interpret(parse_tree);
      $display(i.get_json_val().convert2string());
    end
  end
endprogram

